#!/usr/bin/env node
/**
 * Emit sandboxed Electron preload as CommonJS (ADR-0008).
 * Electron's sandbox loader does not treat package "type":"module" .js as ESM.
 *
 *   node apps/desktop/scripts/emit-preload.mjs
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const APP_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(APP_ROOT, "dist", "preload-app.cjs");

const source = `"use strict";
/**
 * Generated by scripts/emit-preload.mjs — do not edit.
 * Sandboxed preload must be CommonJS (no import/export).
 */
const { contextBridge, ipcRenderer } = require("electron");

const DESKTOP_IPC = {
  localeGet: "xrk-desktop:locale-get",
  updatesCheck: "xrk-desktop:updates-check",
  updatesInstall: "xrk-desktop:updates-install",
  updatesState: "xrk-desktop:updates-state",
};
const DESKTOP_BRIDGE_PROTOCOL_VERSION = 1;

const api = {
  protocolVersion: DESKTOP_BRIDGE_PROTOCOL_VERSION,
  locale: () => ipcRenderer.invoke(DESKTOP_IPC.localeGet),
  updates: {
    check: () => ipcRenderer.invoke(DESKTOP_IPC.updatesCheck),
    install: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.updatesInstall);
    },
    subscribe: (listener) => {
      const handle = (_event, state) => {
        listener(state);
      };
      ipcRenderer.on(DESKTOP_IPC.updatesState, handle);
      return () => {
        ipcRenderer.off(DESKTOP_IPC.updatesState, handle);
      };
    },
  },
};

contextBridge.exposeInMainWorld("xrkDesktop", api);

// Desktop owns the private Host. Face is same-origin xrk-app:// + framed pipes.
contextBridge.exposeInMainWorld("__XRK_TRANSPORT__", {
  ownsHost: true,
});
`;

writeFileSync(OUT, source, "utf8");
process.stdout.write(`emit-preload: ${path.relative(APP_ROOT, OUT)}\n`);
