#!/usr/bin/env node
/**
 * Emit sandboxed Electron preload as CommonJS (ADR-0008).
 * Electron's sandbox loader does not treat package "type":"module" .js as ESM.
 *
 *   node apps/desktop/scripts/emit-preload.mjs
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const APP_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(APP_ROOT, "dist", "preload-app.cjs");

const source = `"use strict";
/**
 * Generated by scripts/emit-preload.mjs — do not edit.
 * Sandboxed preload must be CommonJS (no import/export).
 */
const { contextBridge, ipcRenderer, webUtils } = require("electron");

const DESKTOP_IPC = {
  localeGet: "xrk-desktop:locale-get",
  appVersion: "xrk-desktop:app-version",
  updatesCheck: "xrk-desktop:updates-check",
  updatesInstall: "xrk-desktop:updates-install",
  updatesSnapshot: "xrk-desktop:updates-snapshot",
  updatesState: "xrk-desktop:updates-state",
  windowMinimize: "xrk-desktop:window-minimize",
  windowMaximizeToggle: "xrk-desktop:window-maximize-toggle",
  windowClose: "xrk-desktop:window-close",
  windowIsMaximized: "xrk-desktop:window-is-maximized",
  windowMaximized: "xrk-desktop:window-maximized",
  windowReload: "xrk-desktop:window-reload",
  hostReadyGet: "xrk-desktop:host-ready-get",
  hostReady: "xrk-desktop:host-ready",
  hostFailed: "xrk-desktop:host-failed",
  hostPhaseGet: "xrk-desktop:host-phase-get",
  hostPhase: "xrk-desktop:host-phase",
};
const DESKTOP_BRIDGE_PROTOCOL_VERSION = 1;

const api = {
  protocolVersion: DESKTOP_BRIDGE_PROTOCOL_VERSION,
  platform: process.platform,
  locale: () => ipcRenderer.invoke(DESKTOP_IPC.localeGet),
  version: () => ipcRenderer.invoke(DESKTOP_IPC.appVersion),
  updates: {
    check: () => ipcRenderer.invoke(DESKTOP_IPC.updatesCheck),
    snapshot: () => ipcRenderer.invoke(DESKTOP_IPC.updatesSnapshot),
    install: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.updatesInstall);
    },
    subscribe: (listener) => {
      const handle = (_event, state) => {
        listener(state);
      };
      ipcRenderer.on(DESKTOP_IPC.updatesState, handle);
      return () => {
        ipcRenderer.off(DESKTOP_IPC.updatesState, handle);
      };
    },
  },
  window: {
    minimize: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.windowMinimize);
    },
    toggleMaximize: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.windowMaximizeToggle);
    },
    close: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.windowClose);
    },
    isMaximized: () => ipcRenderer.invoke(DESKTOP_IPC.windowIsMaximized),
    subscribeMaximized: (listener) => {
      const handle = (_event, maximized) => {
        listener(maximized === true);
      };
      ipcRenderer.on(DESKTOP_IPC.windowMaximized, handle);
      return () => {
        ipcRenderer.off(DESKTOP_IPC.windowMaximized, handle);
      };
    },
    reload: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.windowReload);
    },
  },
  files: {
    pathForFile: (file) => {
      try {
        const filePath = webUtils.getPathForFile(file);
        return typeof filePath === "string" && filePath.trim() !== ""
          ? filePath
          : undefined;
      } catch {
        return undefined;
      }
    },
  },
};

contextBridge.exposeInMainWorld("xrkDesktop", api);

function whenHostReady() {
  return new Promise((resolve, reject) => {
    const cleanup = (onReady, onFailed) => {
      ipcRenderer.off(DESKTOP_IPC.hostReady, onReady);
      ipcRenderer.off(DESKTOP_IPC.hostFailed, onFailed);
    };
    void ipcRenderer.invoke(DESKTOP_IPC.hostReadyGet).then((ready) => {
      if (ready === true) {
        setHostPhase("ready");
        resolve();
        return;
      }
      const onReady = () => {
        cleanup(onReady, onFailed);
        setHostPhase("ready");
        resolve();
      };
      const onFailed = (_event, message) => {
        cleanup(onReady, onFailed);
        reject(
          new Error(
            typeof message === "string" && message.trim() !== ""
              ? message
              : "Desktop Host failed to start",
          ),
        );
      };
      ipcRenderer.on(DESKTOP_IPC.hostReady, onReady);
      ipcRenderer.on(DESKTOP_IPC.hostFailed, onFailed);
    });
  });
}

let hostPhase = "starting";
const hostPhaseListeners = new Set();

function isHostPhase(value) {
  return value === "starting" || value === "attaching" || value === "ready";
}

function setHostPhase(phase) {
  if (hostPhase === phase) return;
  hostPhase = phase;
  for (const listener of hostPhaseListeners) listener(phase);
}

ipcRenderer.on(DESKTOP_IPC.hostPhase, (_event, phase) => {
  if (isHostPhase(phase)) setHostPhase(phase);
});

void ipcRenderer.invoke(DESKTOP_IPC.hostPhaseGet).then((phase) => {
  if (isHostPhase(phase)) setHostPhase(phase);
});

function getHostPhase() {
  return hostPhase;
}

function subscribeHostPhase(listener) {
  hostPhaseListeners.add(listener);
  return () => {
    hostPhaseListeners.delete(listener);
  };
}

// Desktop owns the private Host. Product UI stays on xrk-app://; Face is
// proxied to the loopback Host after ready. whenHostReady gates Face connect.
contextBridge.exposeInMainWorld("__XRK_TRANSPORT__", {
  ownsHost: true,
  whenHostReady,
  getHostPhase,
  subscribeHostPhase,
});
`;

writeFileSync(OUT, source, "utf8");
process.stdout.write(`emit-preload: ${path.relative(APP_ROOT, OUT)}\n`);
