#!/usr/bin/env node
/**
 * Emit sandboxed Electron preload as CommonJS (ADR-0008).
 * Electron's sandbox loader does not treat package "type":"module" .js as ESM.
 *
 *   node apps/desktop/scripts/emit-preload.mjs
 *
 * Keep in sync with src/preload-app.ts (+ host-ready-wait listen-first gate).
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const APP_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(APP_ROOT, "dist", "preload-app.cjs");

const source = `"use strict";
/**
 * Generated by scripts/emit-preload.mjs — do not edit.
 * Sandboxed preload must be CommonJS (no import/export).
 */
const { contextBridge, ipcRenderer, webUtils } = require("electron");

const DESKTOP_IPC = {
  localeGet: "xrk-desktop:locale-get",
  appVersion: "xrk-desktop:app-version",
  updatesCheck: "xrk-desktop:updates-check",
  updatesInstall: "xrk-desktop:updates-install",
  updatesSnapshot: "xrk-desktop:updates-snapshot",
  updatesState: "xrk-desktop:updates-state",
  windowMinimize: "xrk-desktop:window-minimize",
  windowMaximizeToggle: "xrk-desktop:window-maximize-toggle",
  windowClose: "xrk-desktop:window-close",
  windowIsMaximized: "xrk-desktop:window-is-maximized",
  windowMaximized: "xrk-desktop:window-maximized",
  windowReload: "xrk-desktop:window-reload",
  hostReadyGet: "xrk-desktop:host-ready-get",
  hostReady: "xrk-desktop:host-ready",
  hostFailed: "xrk-desktop:host-failed",
  hostFailedGet: "xrk-desktop:host-failed-get",
  hostPhaseGet: "xrk-desktop:host-phase-get",
  hostPhase: "xrk-desktop:host-phase",
  hostRebring: "xrk-desktop:host-rebring",
};
const DESKTOP_BRIDGE_PROTOCOL_VERSION = 1;

const api = {
  protocolVersion: DESKTOP_BRIDGE_PROTOCOL_VERSION,
  platform: process.platform,
  locale: () => ipcRenderer.invoke(DESKTOP_IPC.localeGet),
  version: () => ipcRenderer.invoke(DESKTOP_IPC.appVersion),
  updates: {
    check: () => ipcRenderer.invoke(DESKTOP_IPC.updatesCheck),
    snapshot: () => ipcRenderer.invoke(DESKTOP_IPC.updatesSnapshot),
    install: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.updatesInstall);
    },
    subscribe: (listener) => {
      const handle = (_event, state) => {
        listener(state);
      };
      ipcRenderer.on(DESKTOP_IPC.updatesState, handle);
      return () => {
        ipcRenderer.off(DESKTOP_IPC.updatesState, handle);
      };
    },
  },
  window: {
    minimize: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.windowMinimize);
    },
    toggleMaximize: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.windowMaximizeToggle);
    },
    close: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.windowClose);
    },
    isMaximized: () => ipcRenderer.invoke(DESKTOP_IPC.windowIsMaximized),
    subscribeMaximized: (listener) => {
      const handle = (_event, maximized) => {
        listener(maximized === true);
      };
      ipcRenderer.on(DESKTOP_IPC.windowMaximized, handle);
      return () => {
        ipcRenderer.off(DESKTOP_IPC.windowMaximized, handle);
      };
    },
    reload: async () => {
      await ipcRenderer.invoke(DESKTOP_IPC.windowReload);
    },
  },
  files: {
    pathForFile: (file) => {
      try {
        const filePath = webUtils.getPathForFile(file);
        return typeof filePath === "string" && filePath.trim() !== ""
          ? filePath
          : undefined;
      } catch {
        return undefined;
      }
    },
  },
};

contextBridge.exposeInMainWorld("xrkDesktop", api);

/** Listen-first Host Fetch gate (mirrors src/host-ready-wait.ts). */
function waitForHostReady(ports) {
  return new Promise((resolve, reject) => {
    let settled = false;
    let unsubReady = () => {};
    let unsubFailed = () => {};
    const settle = (fn) => {
      if (settled) return;
      settled = true;
      unsubReady();
      unsubFailed();
      fn();
    };
    unsubReady = ports.onReady(() => {
      settle(() => {
        resolve();
      });
    });
    unsubFailed = ports.onFailed((message) => {
      settle(() => {
        reject(
          new Error(
            message.trim() !== "" ? message : "Desktop Host failed to start",
          ),
        );
      });
    });
    void (async () => {
      try {
        if (await ports.getReady()) {
          settle(() => {
            resolve();
          });
          return;
        }
        const failed = await ports.getFailed();
        if (failed !== null && failed.trim() !== "") {
          settle(() => {
            reject(new Error(failed));
          });
        }
      } catch (error) {
        settle(() => {
          reject(error instanceof Error ? error : new Error(String(error)));
        });
      }
    })();
  });
}

let hostPhase = "starting";
const hostPhaseListeners = new Set();
const hostReadyListeners = new Set();

function isHostPhase(value) {
  return value === "starting" || value === "attaching" || value === "ready";
}

function setHostPhase(phase) {
  if (hostPhase === phase) return;
  hostPhase = phase;
  for (const listener of hostPhaseListeners) listener(phase);
}

ipcRenderer.on(DESKTOP_IPC.hostPhase, (_event, phase) => {
  if (isHostPhase(phase)) setHostPhase(phase);
});

ipcRenderer.on(DESKTOP_IPC.hostReady, () => {
  setHostPhase("ready");
  for (const listener of hostReadyListeners) listener();
});

void ipcRenderer.invoke(DESKTOP_IPC.hostPhaseGet).then((phase) => {
  if (isHostPhase(phase)) setHostPhase(phase);
});

function whenHostReady() {
  return waitForHostReady({
    getReady: async () => {
      const ready = await ipcRenderer.invoke(DESKTOP_IPC.hostReadyGet);
      if (ready === true) setHostPhase("ready");
      return ready === true;
    },
    getFailed: async () => {
      const failed = await ipcRenderer.invoke(DESKTOP_IPC.hostFailedGet);
      return typeof failed === "string" ? failed : null;
    },
    onReady: (listener) => {
      const handle = () => {
        listener();
      };
      ipcRenderer.on(DESKTOP_IPC.hostReady, handle);
      return () => {
        ipcRenderer.off(DESKTOP_IPC.hostReady, handle);
      };
    },
    onFailed: (listener) => {
      const handle = (_event, message) => {
        listener(
          typeof message === "string" && message.trim() !== ""
            ? message
            : "Desktop Host failed to start",
        );
      };
      ipcRenderer.on(DESKTOP_IPC.hostFailed, handle);
      return () => {
        ipcRenderer.off(DESKTOP_IPC.hostFailed, handle);
      };
    },
  }).then(() => {
    setHostPhase("ready");
  });
}

function getHostPhase() {
  return hostPhase;
}

function subscribeHostPhase(listener) {
  hostPhaseListeners.add(listener);
  return () => {
    hostPhaseListeners.delete(listener);
  };
}

function subscribeHostReady(listener) {
  hostReadyListeners.add(listener);
  return () => {
    hostReadyListeners.delete(listener);
  };
}

function requestHostRebring() {
  return ipcRenderer.invoke(DESKTOP_IPC.hostRebring).then(() => undefined);
}

// Desktop owns the private Host. Product UI stays on xrk-app://; Face is
// proxied to the loopback Host after ready. whenHostReady gates Face connect.
contextBridge.exposeInMainWorld("__XRK_TRANSPORT__", {
  ownsHost: true,
  whenHostReady,
  getHostPhase,
  subscribeHostPhase,
  subscribeHostReady,
  requestHostRebring,
});
`;

writeFileSync(OUT, source, "utf8");
process.stdout.write(`emit-preload: ${path.relative(APP_ROOT, OUT)}\n`);
