import type { BrandEntry } from "./types.js";

/** Locked BrandEntries for openai-chat (docs/llm-provider-presets.md). */
export const OPENAI_CHAT_BRANDS: readonly BrandEntry[] = [
  {
    id: "openai",
    displayName: "OpenAI",
    protocol: "openai-chat",
    baseUrl: "https://api.openai.com/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "OPENAI_API_KEY",
  },
  {
    id: "deepseek",
    displayName: "DeepSeek（兼容面）",
    protocol: "openai-chat",
    baseUrl: "https://api.deepseek.com",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "DEEPSEEK_API_KEY",
    defaultModel: "deepseek-v4-flash",
  },
  {
    id: "opencode",
    displayName: "OpenCode Zen",
    protocol: "openai-chat",
    baseUrl: "https://opencode.ai/zen/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "OPENCODE_API_KEY",
    defaultModel: "big-pickle",
    notes: "API key from https://opencode.ai/zen",
  },
  {
    id: "opencode-go",
    displayName: "OpenCode Go",
    protocol: "openai-chat",
    baseUrl: "https://opencode.ai/zen/go/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "OPENCODE_GO_API_KEY",
    defaultModel: "deepseek-v4-flash",
    notes: "OPENCODE_API_KEY accepted as env fallback",
  },
  {
    id: "openrouter",
    displayName: "OpenRouter",
    protocol: "openai-chat",
    baseUrl: "https://openrouter.ai/api/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "OPENROUTER_API_KEY",
  },
  {
    id: "groq",
    displayName: "Groq",
    protocol: "openai-chat",
    baseUrl: "https://api.groq.com/openai/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "GROQ_API_KEY",
  },
  {
    id: "fireworks",
    displayName: "Fireworks",
    protocol: "openai-chat",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "FIREWORKS_API_KEY",
  },
  {
    id: "together",
    displayName: "Together",
    protocol: "openai-chat",
    baseUrl: "https://api.together.xyz/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "TOGETHER_API_KEY",
  },
  {
    id: "github-models",
    displayName: "GitHub Models",
    protocol: "openai-chat",
    baseUrl: "https://models.inference.ai.azure.com",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "GITHUB_TOKEN",
  },
  {
    id: "xai",
    displayName: "xAI",
    protocol: "openai-chat",
    baseUrl: "https://api.x.ai/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "XAI_API_KEY",
  },
  {
    id: "mistral",
    displayName: "Mistral",
    protocol: "openai-chat",
    baseUrl: "https://api.mistral.ai/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "MISTRAL_API_KEY",
  },
  {
    id: "cerebras",
    displayName: "Cerebras",
    protocol: "openai-chat",
    baseUrl: "https://api.cerebras.ai/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "CEREBRAS_API_KEY",
  },
  {
    id: "deepinfra",
    displayName: "Deep Infra",
    protocol: "openai-chat",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "DEEPINFRA_API_KEY",
  },
  {
    id: "novita-ai",
    displayName: "NovitaAI",
    protocol: "openai-chat",
    baseUrl: "https://api.novita.ai/openai",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "NOVITA_API_KEY",
  },
  {
    id: "siliconflow",
    displayName: "SiliconFlow",
    protocol: "openai-chat",
    baseUrl: "https://api.siliconflow.com/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "SILICONFLOW_API_KEY",
  },
  {
    id: "siliconflow-cn",
    displayName: "SiliconFlow (China)",
    protocol: "openai-chat",
    baseUrl: "https://api.siliconflow.cn/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "SILICONFLOW_CN_API_KEY",
  },
  {
    id: "moonshotai",
    displayName: "Moonshot AI",
    protocol: "openai-chat",
    baseUrl: "https://api.moonshot.ai/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "MOONSHOT_API_KEY",
  },
  {
    id: "moonshotai-cn",
    displayName: "Moonshot AI (China)",
    protocol: "openai-chat",
    baseUrl: "https://api.moonshot.cn/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "MOONSHOT_API_KEY",
  },
  {
    id: "minimax",
    displayName: "MiniMax (minimax.io)",
    protocol: "openai-chat",
    baseUrl: "https://api.minimax.io/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "MINIMAX_API_KEY",
  },
  {
    id: "minimax-cn",
    displayName: "MiniMax (minimaxi.com)",
    protocol: "openai-chat",
    baseUrl: "https://api.minimaxi.com/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "MINIMAX_API_KEY",
  },
  {
    id: "zai",
    displayName: "Z.AI",
    protocol: "openai-chat",
    baseUrl: "https://api.z.ai/api/paas/v4",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "ZHIPU_API_KEY",
  },
  {
    id: "zhipuai",
    displayName: "Zhipu AI",
    protocol: "openai-chat",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "ZHIPU_API_KEY",
  },
  {
    id: "perplexity",
    displayName: "Perplexity",
    protocol: "openai-chat",
    baseUrl: "https://api.perplexity.ai",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "PERPLEXITY_API_KEY",
  },
  {
    id: "huggingface",
    displayName: "Hugging Face",
    protocol: "openai-chat",
    baseUrl: "https://router.huggingface.co/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "HF_TOKEN",
  },
  {
    id: "nvidia",
    displayName: "Nvidia",
    protocol: "openai-chat",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "NVIDIA_API_KEY",
  },
  {
    id: "baseten",
    displayName: "Baseten",
    protocol: "openai-chat",
    baseUrl: "https://inference.baseten.co/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "BASETEN_API_KEY",
  },
  {
    id: "vercel",
    displayName: "Vercel AI Gateway",
    protocol: "openai-chat",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "AI_GATEWAY_API_KEY",
  },
  {
    id: "aihubmix",
    displayName: "AIHubMix",
    protocol: "openai-chat",
    baseUrl: "https://aihubmix.com/v1",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "AIHUBMIX_API_KEY",
  },
  {
    id: "ollama",
    displayName: "Ollama（OpenAI 兼容端口）",
    protocol: "openai-chat",
    baseUrl: "http://127.0.0.1:11434/v1",
    path: "/chat/completions",
    authMode: "bearer",
    notes: "Often no API key; full ollama protocol is R1",
  },
  {
    id: "lmstudio",
    displayName: "LM Studio",
    protocol: "openai-chat",
    baseUrl: "http://127.0.0.1:1234/v1",
    path: "/chat/completions",
    authMode: "bearer",
    notes: "Local OpenAI-compatible server; often no API key",
  },
  {
    id: "azure-openai",
    displayName: "Azure OpenAI（简易）",
    protocol: "openai-chat",
    path: "/chat/completions",
    authMode: "api-key",
    apiKeyEnv: "AZURE_OPENAI_API_KEY",
    notes: "baseUrl required; full Azure deployment path is R1",
  },
  {
    id: "newapi",
    displayName: "New API",
    protocol: "openai-chat",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "NEWAPI_API_KEY",
    notes: "Self-hosted; baseUrl required",
  },
  {
    id: "cherryin",
    displayName: "CherryIN",
    protocol: "openai-chat",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "CHERRYIN_API_KEY",
    notes: "Self-hosted; baseUrl required",
  },
  {
    id: "custom",
    displayName: "Custom OpenAI-compatible",
    protocol: "openai-chat",
    path: "/chat/completions",
    authMode: "bearer",
    apiKeyEnv: "OPENAI_API_KEY",
    notes: "baseUrl required",
  },
];

const byId = new Map(OPENAI_CHAT_BRANDS.map((b) => [b.id, b]));

export function getOpenAiChatBrand(id: string): BrandEntry | undefined {
  return byId.get(id.trim().toLowerCase());
}
